name: Automated Tests

on:
  workflow_dispatch:
    inputs:
      deployment_target:
        description: Choose target
        required: true
        default:
        type: choice
        options:
          - test_click_button_exams
          - test_click_legalisation_button
          - test_click_about_us_button
          - test_click_contact_button
          - test_click_ukrainian_version_button
          - test_click_pl_button
          - test_click_ru_button
          -


jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python env
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Chrome
        run: sudo apt-get install google-chrome-stable

      - name: Clear pip cache
        run: pip cache purge

      - name: Install dependencies
        run: pip install -r requirements.txt

#      - name: Start virtual display
#        run: |
#          sudo apt-get install xvfb
#          Xvfb :99 & export DISPLAY=:99

      - name: Run test_click_button_exams
        if: "github.event.inputs.deployment_target == 'test_click_button_exams'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_button_exams


      - name: Run test_click_legalisation_button
        if: "github.event.inputs.deployment_target == 'test_click_legalisation_button'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_legalisation_button


      - name: Run test_click_about_us_button
        if: "github.event.inputs.deployment_target == 'test_click_about_us_button'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_about_us_button


      - name: Run test_click_contact_button
        if: "github.event.inputs.deployment_target == 'test_click_contact_button'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_contact_button


      - name: Run test_click_ukrainian_version_button
        if: "github.event.inputs.deployment_target == 'test_click_ukrainian_version_button'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_ukrainian_version_button


      - name: Run test_click_pl_button
        if: "github.event.inputs.deployment_target == 'test_click_pl_button'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_pl_button


      - name: Run test_click_ru_button
        if: "github.event.inputs.deployment_target == 'test_click_ru_button'"
        env:
          DISPLAY: :99
        run: PYTHONPATH=. pytest tests/test_home_page.py::test_click_ru_button


